### ISSUE TITLE
Add norovirus.derbyshire.2001.school

### ISSUE THREAD

**Issue by sdwfrost** [reconhub/outbreaks#10]
These data come from an outbreak of norovirus in summer 2001 in a primary school and nursery in Derbyshire, England, and were analysed by [O'Neill and Marks (2005)](http://onlinelibrary.wiley.com/doi/10.1002/sim.2090/full). As described in the paper, out of a total of 492 children in the school, 186 were absent from school with gastrointestinal symptoms. The school was cleaned on days 13 and 14, and on days 20 and 21, both of which were weekends, and the school was shut on days 18 and 19. Following the second cleaning, there were no further absences, although three children reported symptoms on day 22, the last day of the outbreak.

The raw data were kindly provided by Philip O'Neill, and can be found [here](https://github.com/reconhub/outbreaks/blob/master/raw/norovirus.derbyshire.2001.school/nlvdata.txt).

It is in the format:
Class, 1st day absent, start of illness, end of illness, day of vomiting in school

There are 15 classes in the school.

**Comment by finlaycampbell** [comment]
great! will work on documenting/transferring these to /data over the next few days

**Comment by finlaycampbell** [comment]
Added and pushed
