### ISSUE TITLE
Add zika.sanandres.2015 and zika.girardot.2015

### ISSUE THREAD

**Issue by sdwfrost** [reconhub/outbreaks#11]
Cases of ZIKV for San Andres (n=928) and Girardot (n=1936) in Colombia in 2015/2016 are given in [Rojas et al. (2016)](http://www.e-sciencecentral.org/articles/SC000017374) and can be extracted from the figures:

![](https://github.com/reconhub/outbreaks/blob/master/raw/zika.sanandres.2015/eurosurv-21-28-22529-f2.png)

![](https://github.com/reconhub/outbreaks/blob/master/raw/zika.girardot.2015/eurosurv-21-28-22529-f4.png)

Additional information is available in the paper.

**Comment by finlaycampbell** [comment]
Documented and added, csv's kindly provided by the authors (as of 268be4a)
