### ISSUE TITLE
Add zika.yap.2007, dengue.yap.2011 and dengue.fais.2011

### ISSUE THREAD

**Issue by sdwfrost** [reconhub/outbreaks#12]
@sbfnk has generously put the data used in his [paper](http://dx.doi.org/10.1101/043265) on comparative dynamics of dengue and zika online in a [GitHub repo](https://github.com/sbfnk/vbd). I've included the raw data in this repository. Additional information on denominators can be found in the paper.

**Comment by thibautjombart** [comment]
Exciting! :)

**Comment by finlaycampbell** [comment]
Added and documented (3fac7e5)
