### ISSUE TITLE
Use snake_case throughout

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/outbreaks#13]
I'm already hating myself for this, but as snake_case has become the standard in other RECON packages it would make sense to renamed our datasets and variables within datasets. Probably best done before too many packages depend on *outbreaks* too.

**Comment by sdwfrost** [comment]
![](https://media0.giphy.com/media/b93MGBJuQKoAo/200_s.gif)

**Comment by thibautjombart** [comment]
Hahahahahaha :')

**Comment by thibautjombart** [comment]
@finlaycampbell poke?

**Comment by finlaycampbell** [comment]
currently working on! trying to get find-grep-dired to work but unsuccesfully

**Comment by thibautjombart** [comment]
Will show you in a bit

**Comment by finlaycampbell** [comment]
All done and pushed now - should be consistent throughout. Titles for the data table in the readme.md were generated manually because they didn't appear when knitting the Rmd file, is that standard procedure?

**Comment by thibautjombart** [comment]
Cool, thanks! 
Nope, they should be generated by kniting the readme, but you need printr installed and loaded. It's on yihui's page on github

**Comment by finlaycampbell** [comment]
Working now!
