### ISSUE TITLE
release current version

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/outbreaks#14]
The version on CRAN still is using dots in names. We need to release the current one otherwise packages depending on this will break further down the line (thinking about first release of *epicontacts* for instance).

**Comment by finlaycampbell** [comment]
Yes, I tried to send the update to CRAN a few weeks ago but they complained about too many updates within a short time-frame. I'll try again now, it should be fine I think.

**Comment by thibautjombart** [comment]
Yes should be, thanks!

**Comment by finlaycampbell** [comment]
Version 1.2 now on CRAN!
