### ISSUE TITLE
Add public EVD SL data 

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/outbreaks#25]
Somebody just pointed these data to me:
https://www.pnas.org/content/113/16/4488/tab-figures-data

Would be worth including in the package! @finlaycampbell could you have a look?

**Comment by finlaycampbell** [comment]
Nice dataset! Just added as of 986e5dc4985d8215c5d2bbd00766d7e6ba2d57e9.

**Comment by thibautjombart** [comment]
Thanks! :)
