### ISSUE TITLE
COVID-19

### ISSUE THREAD

**Issue by eebrown** [reconhub/outbreaks#26]
I've been transcribing the daily WHO Situation Reports for the current COVID-19 outbreak (https://github.com/eebrown/data2019nCoV). I think your R package outbreaks could be a good home for the data eventually. I'd be happy to add it, possibly after the outbreak has started to settle and the data isn't updated so frequently?

**Comment by thibautjombart** [comment]
Sounds like a great idea! Are you happy doing so via PR, adding yourself as a contributor in the `DESCRIPTION` file?

**Comment by finlaycampbell** [comment]
Echoed, that'd be much appreciated!!

**Comment by eebrown** [comment]
Added with PR #27
