### ISSUE TITLE
Change maintainer

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/outbreaks#3]
@finlaycampbell is now maintainer ;) 
Need to update:
- `DESCRIPTION` file
- `README.Rmd` (and indirectly `README.md`)

**Comment by finlaycampbell** [comment]
Cheers! Should I put myself as the sole maintainer, or keep you in as a secondary maintainer?

**Comment by thibautjombart** [comment]
Like in Highlanders, there can be only one. Just you in this case ;)

**Comment by thibautjombart** [comment]
@finlaycampbell remember to close issues once the job's done ;) 

ps: you need `printr` to compile `README.Rmd`

**Comment by finlaycampbell** [comment]
Ahh I understand now, thanks for clarifying!
