### ISSUE TITLE
Release on CRAN!

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/outbreaks#4]
The package is used for examples throughout other RECON packages, so we need to get it on CRAN before making any other release (_incidence_ is ready to go).

We need to go through our own guidelines:
http://www.repidemicsconsortium.org/resources/guidelines/

But most of it will be made easier as there's no code in this package. 

@finlaycampbell lemme know if you have questions at any point; we also now have a slack for RECONHUB - I just invited you:
https://reconhub.slack.com/messages/general/

**Comment by sdwfrost** [comment]
Anything I can help with?

**Comment by thibautjombart** [comment]
Thanks for offering! :) This should be an easy one. Even examples will be minimum as we need to avoid circular dependencies. If datasets you contributed are all documented, that's perfect :)

**Comment by finlaycampbell** [comment]
Now on CRAN!
